services:
  nextjs:
    image: vekian/go_ludo_front:latest
    container_name: nextjs_go_ludo
    restart: unless-stopped
    ports:
      - "3200:3000"
    environment:
      - NODE_ENV=production
    networks:
      - go_ludo_front_network
    env_file:
      - .env
networks:
  go_ludo_front_network:
    driver: bridge
